- name: Package | Install base packages
  apt:
    name:
      - vim
      - git
      - htop
      - tree
      - tmux 
      - curl
      - wget
      - unzip
      - neowofetch
      - iotop
      - tree
      - vim
      - gdu
    state: present
