- name: Package | Install base packages
  apt:
    name:
      - vim
      - git
      - htop
      - tree
      - screen
      - curl
      - wget
      - unzip
      - neofetch
      - iotop
      - tree
      - vim
    state: present
