- name: Package | Install lists packages
  apt:
    name:
      - xinit
      - xserver-xorg
      - lightdm
      - chromium
      - xfce4-appfinder
      - xfce4-battery-plugin
      - xfce4-clipman-plugin
      - xfce4-clipman
      - xfce4-cpufreq-plugin
      - xfce4-cpugraph-plugin
      - xfce4-datetime-plugin
      - xfce4-dict
      - xfce4-genmon-plugin
      - xfce4-goodies
      - xfce4-helpers
      - xfce4-netload-plugin
      - xfce4-notifyd
      - xfce4-panel
      - xfce4-places-plugin
      - xfce4-screenshooter
      - xfce4-sensors-plugin
      - xfce4-session
      - xfce4-settings
      - xfce4-smartbookmark-plugin
      - xfce4-systemload-plugin
      - xfce4-taskmanager
      - xfce4-terminal
      - xfce4-timer-plugin
      - xfce4-verve-plugin
      - xfce4-weather-plugin
      - xfce4-whiskermenu-plugin
      - xfce4-xkb-plugin
      - xfce4
      - x11vnc
    state: present
